[platformio]
default_envs = stock_qvga, wide_qvga, vga_software

[env]
platform = https://github.com/DFRobot/platform-unihiker.git
board = unihiker_k10
framework = arduino
monitor_speed = 115200
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

[env:stock_qvga]
build_flags =
    ${env.build_flags}
    -DBENCH_MODE=0

[env:wide_qvga]
build_flags =
    ${env.build_flags}
    -DBENCH_MODE=1

[env:vga_software]
build_flags =
    ${env.build_flags}
    -DBENCH_MODE=2
