[platformio]
default_envs = stock_qvga, wide_qvga, vga_software, sensor_1_4, sensor_full_1_5

[env]
platform = https://github.com/DFRobot/platform-unihiker.git
board = unihiker_k10
framework = arduino
monitor_speed = 115200
extra_scripts = pre:tools/patch_camera_archive.py
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

[env:stock_qvga]
build_flags =
    ${env.build_flags}
    -DBENCH_MODE=0
    -DGC2145_FOV_MODE=0

[env:wide_qvga]
build_flags =
    ${env.build_flags}
    -DBENCH_MODE=1
    -DGC2145_FOV_MODE=1

[env:vga_software]
build_flags =
    ${env.build_flags}
    -DBENCH_MODE=2
    -DGC2145_FOV_MODE=0

[env:sensor_1_4]
build_flags =
    ${env.build_flags}
    -DBENCH_MODE=3
    -DGC2145_FOV_MODE=2

[env:sensor_full_1_5]
build_flags =
    ${env.build_flags}
    -DBENCH_MODE=4
    -DGC2145_FOV_MODE=3
